import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const font = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth hydrated">
      <head>
        <link rel="icon" href="/favicon.ico" />
        {/* <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-46MSP9DWZR"
        ></script>
        <script
          type="text/javascript"
          src="https://popupr.com/js/analytics.js"
        ></script>
        <script
          type="text/javascript"
          src="https://popupr.com/js/clarity.js"
        ></script>
        <script
          defer
          data-domain="popupr.com"
          src="https://popupr.com/js/script.js"
        ></script> */}
      </head>
      <body className={`${font.className} text-gray-800 font-medium`}>
        <AuthProvider>{children}</AuthProvider>
        <Toaster position="top-right" expand={true} richColors />

        <Script
          strategy="afterInteractive"
          async={true}
          src="https://www.googletagmanager.com/gtag/js?id=G-46MSP9DWZR"
        />
        <Script
          strategy="afterInteractive"
          src="https://popupr.com/js/analytics.js"
        />
        <Script
          strategy="afterInteractive"
          src="https://popupr.com/js/clarity.js"
        />
        <Script
          strategy="afterInteractive"
          defer={true}
          data-domain="popupr.com"
          src="https://popupr.com/js/script.js"
        />
      </body>
    </html>
  );
}
